### ISSUE TITLE
Feature Request: Add an endpoint option to the instantiation to enable use with zenhub enterprise accounts

### ISSUE THREAD

**Issue by bski1** [goanpeca/pyzenhub#1]
Thank you for creating this utility. Please add an option to set the endpoint to something other than the public zenhub server similar to what the PyGithub utility does. This will enable use in enterprise zenhub accounts.

From https://pygithub.readthedocs.io/en/latest/introduction.html:

! Github Enterprise with custom hostname
g = Github(base_url="https://{hostname}/api/v3", login_or_token="access_token")

**Comment by goanpeca** [comment]
Will do and make a new release soon ;-)

**Comment by goanpeca** [comment]
@bski1 could you install from source and give it a go, to see if all works as expected?

`python -m pip install git+https://github.com/goanpeca/pyzenhub.git`

Thanks!

**Comment by bski1** [comment]
Hello @goanpeca, I received an error running the pip install during the clone step so I was not able to test the official build, but I did do a quick copy of the source locally and it worked as expected. 

Thank you!

**Comment by goanpeca** [comment]
Ok, will make a release then. Thanks for testing.

**Comment by goanpeca** [comment]
Released!

**Comment by goanpeca** [comment]
This has been implemented.
