### ISSUE TITLE
set_issue_estimate fails with "Unknown Error"

### ISSUE THREAD

**Issue by carl-mayer** [goanpeca/pyzenhub#4]
Attempting to set_issue_estimate results in the following error.

    result = zh.set_issue_estimate(repo_id, issue_number, estimate)
  File "/Users/.../zenhub/core.py", line 161, in set_issue_estimate
    return self._put(url, body)
  File "/Users/.../zenhub/core.py", line 99, in _put
    return self._parse_response_contents(response)
  File "/Users/.../zenhub/core.py", line 70, in _parse_response_contents
    raise ZenhubError("Unknown error!")
zenhub.core.ZenhubError: Unknown error!

Looking into the details ZenHub returns a status code of 400 along with "message":"invalid json".

changing line 98 in core.py resolved the issue:
       - response = self._session.put(url=self._make_url(url), data=body)
       + response = self._session.put(url=self._make_url(url), json=body)

**Comment by goanpeca** [comment]
Hi @carl-mayer thanks for the report and the fix.

Do you want to open a PR with it?

Cheers

**Comment by salob** [comment]
@goanpeca see #6 please review

FYI @georgec-s, I believe you were also seeing this issue and used the raw API for some requests
